### ISSUE TITLE
Missing build items

### ISSUE THREAD

**Issue by techhazard** [figure002/nextwall#2]
When trying to build:

The compiler and auto tools are missing: 
`apt-get install build-essential automake check lib[...]`
(this should install `autotools-dev` as a dependency)

There is also no `./configure` file after cloning which I would expect after compiling other C(++) programs from source. Take https://github.com/gcc-mirror/gcc as example

**Comment by figure002** [comment]
I chose to not include generated files in the repository. This includes the `configure` script which can be easily created by following the instructions in the README. When distributing source packages, however, I would include the `configure` script.

I probably should include `build-essential` and `automake` in the requirements.
