### ISSUE TITLE
[Idea] Use travis for automated testing

### ISSUE THREAD

**Issue by techhazard** [figure002/nextwall#3]
Add travis CI for automated testing

see: https://docs.travis-ci.com/user/languages/c/

(this is free for all public github repos and integrates very well)

**Comment by figure002** [comment]
I already use this; see the nice build button on the README page (which is currently failing).

**Comment by figure002** [comment]
Though I must say that the current tests are pretty useless and not at all deterministic.

**Comment by techhazard** [comment]
whoops! my bad 😲
